[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32.git#master
platform_packages =
    framework-arduinoespressif32 @ https://github.com/pioarduino/arduino-esp32#master
    framework-arduinoespressif32-libs @ https://github.com/pioarduino/esp32-arduino-libs#master
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    links2004/WebSockets@^2.5.4

build_flags =
    -DCORE_DEBUG_LEVEL=3
