
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ZLAC8015D_H
#define ZLAC8015D_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 ZLAC8015D_valueRangeTest (UNS8 typeValue, void * value);
const indextable * ZLAC8015D_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ZLAC8015D_Data;
extern UNS16 commu_protect;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 RS485_Node_ID;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 RS485_Baud_Rate;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 Input_Status;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 Output_Status;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 Pos_Feedback_Clear;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 Abs_Pos_Clear;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS8 Enable_PowerOn;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 Motor_Max_Velocity;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 Factory_Reset;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 CAN_NodeID;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS16 CAN_Baud_Rate;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 Motor_Pole[2];		/* Mapped at index 0x200C, subindex 0x01 - 0x02 */
extern UNS16 Start_Velocity[2];		/* Mapped at index 0x200D, subindex 0x01 - 0x02 */
extern UNS16 Encoder_Line[2];		/* Mapped at index 0x200E, subindex 0x01 - 0x02 */
extern UNS16 Control_Status;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS16 EEPROM_Config;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 Hall_Angle[2];		/* Mapped at index 0x2011, subindex 0x01 - 0x02 */
extern UNS16 Overload_Factor[2];		/* Mapped at index 0x2012, subindex 0x01 - 0x02 */
extern UNS16 Temperature_Threshold[2];		/* Mapped at index 0x2013, subindex 0x01 - 0x02 */
extern UNS16 Rated_Current[2];		/* Mapped at index 0x2014, subindex 0x01 - 0x02 */
extern UNS16 Max_Current[2];		/* Mapped at index 0x2015, subindex 0x01 - 0x02 */
extern UNS16 Overload_Protect_timer[2];		/* Mapped at index 0x2016, subindex 0x01 - 0x02 */
extern UNS16 OverPos_Threshold[2];		/* Mapped at index 0x2017, subindex 0x01 - 0x02 */
extern UNS16 velocity_smoothing_factor[2];		/* Mapped at index 0x2018, subindex 0x01 - 0x02 */
extern UNS16 cl_kp[2];		/* Mapped at index 0x2019, subindex 0x01 - 0x02 */
extern UNS16 cl_ki[2];		/* Mapped at index 0x201A, subindex 0x01 - 0x02 */
extern UNS16 ff_smoth_factor[2];		/* Mapped at index 0x201B, subindex 0x01 - 0x02 */
extern UNS16 torque_smoth_factor[2];		/* Mapped at index 0x201C, subindex 0x01 - 0x02 */
extern UNS16 vl_kp[2];		/* Mapped at index 0x201D, subindex 0x01 - 0x02 */
extern UNS16 vl_ki[2];		/* Mapped at index 0x201E, subindex 0x01 - 0x02 */
extern UNS16 vl_kf[2];		/* Mapped at index 0x201F, subindex 0x01 - 0x02 */
extern UNS16 pl_kp[2];		/* Mapped at index 0x2020, subindex 0x01 - 0x02 */
extern UNS16 pl_kf[2];		/* Mapped at index 0x2021, subindex 0x01 - 0x02 */
extern UNS16 velocity_observer_1[2];		/* Mapped at index 0x2022, subindex 0x01 - 0x02 */
extern UNS16 velocity_observer_2[2];		/* Mapped at index 0x2023, subindex 0x01 - 0x02 */
extern UNS16 velocity_observer_3[2];		/* Mapped at index 0x2024, subindex 0x01 - 0x02 */
extern UNS16 velocity_observer_4[2];		/* Mapped at index 0x2025, subindex 0x01 - 0x02 */
extern UNS16 IO_config[8];		/* Mapped at index 0x2030, subindex 0x01 - 0x08 */
extern UNS16 software_version;		/* Mapped at index 0x2031, subindex 0x00*/
extern UNS16 motor_temperature[2];		/* Mapped at index 0x2032, subindex 0x01 - 0x02 */
extern UNS16 mortor_status[2];		/* Mapped at index 0x2033, subindex 0x01 - 0x02 */
extern UNS16 Hall_status[2];		/* Mapped at index 0x2034, subindex 0x01 - 0x02 */
extern UNS16 DC_voltage;		/* Mapped at index 0x2035, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER8 Modes_of_operation;		/* Mapped at index 0x6060, subindex 0x00*/
extern INTEGER8 Modes_of_operation_display;		/* Mapped at index 0x6061, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6064, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern UNS32 Profile_acceleration;		/* Mapped at index 0x6083, subindex 0x00*/
extern UNS32 Profile_deceleration;		/* Mapped at index 0x6084, subindex 0x00*/
extern UNS32 Quick_stop_deceleration;		/* Mapped at index 0x6085, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // ZLAC8015D_H
