[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200

; Enable USB Host for Xbox controller
build_flags = -D USB_SERIAL_HID

lib_deps =
    https://github.com/joepasquariello/FlasherX.git
