
/* File generated by gen_cfile.py. Should not be modified. */

#include "ZLAC8015D.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 commu_protect = 0x3E8;		/* Mapped at index 0x2000, subindex 0x00 */
UNS16 RS485_Node_ID = 0x1;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 RS485_Baud_Rate = 0x2;		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Input_Status = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 Output_Status = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 Pos_Feedback_Clear = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS16 Abs_Pos_Clear = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS8 Enable_PowerOn = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS16 Motor_Max_Velocity = 0x3E8;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 Factory_Reset = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS16 CAN_NodeID = 0x1;		/* Mapped at index 0x200A, subindex 0x00 */
UNS16 CAN_Baud_Rate = 0x1;		/* Mapped at index 0x200B, subindex 0x00 */
UNS16 Motor_Pole[] =		/* Mapped at index 0x200C, subindex 0x01 - 0x02 */
  {
    0xF,	/* 15 */
    0xF	/* 15 */
  };
UNS16 Start_Velocity[] =		/* Mapped at index 0x200D, subindex 0x01 - 0x02 */
  {
    0x1,	/* 1 */
    0x1	/* 1 */
  };
UNS16 Encoder_Line[] =		/* Mapped at index 0x200E, subindex 0x01 - 0x02 */
  {
    0x400,	/* 1024 */
    0x400	/* 1024 */
  };
UNS16 Control_Status = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS16 EEPROM_Config = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS16 Hall_Angle[] =		/* Mapped at index 0x2011, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Overload_Factor[] =		/* Mapped at index 0x2012, subindex 0x01 - 0x02 */
  {
    0xC8,	/* 200 */
    0xC8	/* 200 */
  };
UNS16 Temperature_Threshold[] =		/* Mapped at index 0x2013, subindex 0x01 - 0x02 */
  {
    0x320,	/* 800 */
    0x320	/* 800 */
  };
UNS16 Rated_Current[] =		/* Mapped at index 0x2014, subindex 0x01 - 0x02 */
  {
    0x96,	/* 150 */
    0x96	/* 150 */
  };
UNS16 Max_Current[] =		/* Mapped at index 0x2015, subindex 0x01 - 0x02 */
  {
    0x12C,	/* 300 */
    0x12C	/* 300 */
  };
UNS16 Overload_Protect_timer[] =		/* Mapped at index 0x2016, subindex 0x01 - 0x02 */
  {
    0x12C,	/* 300 */
    0x12C	/* 300 */
  };
UNS16 OverPos_Threshold[] =		/* Mapped at index 0x2017, subindex 0x01 - 0x02 */
  {
    0x199,	/* 409 */
    0x199	/* 409 */
  };
UNS16 velocity_smoothing_factor[] =		/* Mapped at index 0x2018, subindex 0x01 - 0x02 */
  {
    0x32,	/* 50 */
    0x32	/* 50 */
  };
UNS16 cl_kp[] =		/* Mapped at index 0x2019, subindex 0x01 - 0x02 */
  {
    0x258,	/* 600 */
    0x258	/* 600 */
  };
UNS16 cl_ki[] =		/* Mapped at index 0x201A, subindex 0x01 - 0x02 */
  {
    0x12C,	/* 300 */
    0x12C	/* 300 */
  };
UNS16 ff_smoth_factor[] =		/* Mapped at index 0x201B, subindex 0x01 - 0x02 */
  {
    0x64,	/* 100 */
    0x64	/* 100 */
  };
UNS16 torque_smoth_factor[] =		/* Mapped at index 0x201C, subindex 0x01 - 0x02 */
  {
    0x64,	/* 100 */
    0x64	/* 100 */
  };
UNS16 vl_kp[] =		/* Mapped at index 0x201D, subindex 0x01 - 0x02 */
  {
    0x1F4,	/* 500 */
    0x1F4	/* 500 */
  };
UNS16 vl_ki[] =		/* Mapped at index 0x201E, subindex 0x01 - 0x02 */
  {
    0x3E8,	/* 1000 */
    0x3E8	/* 1000 */
  };
UNS16 vl_kf[] =		/* Mapped at index 0x201F, subindex 0x01 - 0x02 */
  {
    0x3E8,	/* 1000 */
    0x3E8	/* 1000 */
  };
UNS16 pl_kp[] =		/* Mapped at index 0x2020, subindex 0x01 - 0x02 */
  {
    0x32,	/* 50 */
    0x32	/* 50 */
  };
UNS16 pl_kf[] =		/* Mapped at index 0x2021, subindex 0x01 - 0x02 */
  {
    0xC8,	/* 200 */
    0xC8	/* 200 */
  };
UNS16 velocity_observer_1[] =		/* Mapped at index 0x2022, subindex 0x01 - 0x02 */
  {
    0x3E8,	/* 1000 */
    0x3E8	/* 1000 */
  };
UNS16 velocity_observer_2[] =		/* Mapped at index 0x2023, subindex 0x01 - 0x02 */
  {
    0x2EE,	/* 750 */
    0x2EE	/* 750 */
  };
UNS16 velocity_observer_3[] =		/* Mapped at index 0x2024, subindex 0x01 - 0x02 */
  {
    0x15E,	/* 350 */
    0x15E	/* 350 */
  };
UNS16 velocity_observer_4[] =		/* Mapped at index 0x2025, subindex 0x01 - 0x02 */
  {
    0x3E8,	/* 1000 */
    0x3E8	/* 1000 */
  };
UNS16 IO_config[] =		/* Mapped at index 0x2030, subindex 0x01 - 0x08 */
  {
    0x0,	/* 0 */
    0x9,	/* 9 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 software_version = 0x0;		/* Mapped at index 0x2031, subindex 0x00 */
UNS16 motor_temperature[] =		/* Mapped at index 0x2032, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 mortor_status[] =		/* Mapped at index 0x2033, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Hall_status[] =		/* Mapped at index 0x2034, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 DC_voltage = 0x0;		/* Mapped at index 0x2035, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x0;		/* Mapped at index 0x6085, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ZLAC8015D_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ZLAC8015D_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ZLAC8015D_iam_a_slave = 1;

TIMER_HANDLE ZLAC8015D_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ZLAC8015D_obj1000 = 0x40192;	/* 262546 */
                    subindex ZLAC8015D_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ZLAC8015D_obj1001 = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ZLAC8015D_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ZLAC8015D_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex ZLAC8015D_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 ZLAC8015D_obj1005 = 0x80;	/* 128 */
                    ODCallback_t ZLAC8015D_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ZLAC8015D_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 ZLAC8015D_obj1006 = 0x0;   /* 0 */

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 ZLAC8015D_obj1009 = (UNS8) 1;
                    subindex ZLAC8015D_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&ZLAC8015D_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 ZLAC8015D_obj100A= (UNS8) 1;
                    subindex ZLAC8015D_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&ZLAC8015D_obj100A }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 ZLAC8015D_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 ZLAC8015D_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 ZLAC8015D_obj1014 = 0x80;	/* 128 */
                    subindex ZLAC8015D_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ZLAC8015D_highestSubIndex_obj1016 = 0;
                    UNS32 ZLAC8015D_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ZLAC8015D_obj1017 = 0x0;	/* 0 */
                    ODCallback_t ZLAC8015D_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ZLAC8015D_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1018_Vendor_ID = 0x100;	/* 256 */
                    UNS32 ZLAC8015D_obj1018_Product_Code = 0x1;	/* 1 */
                    UNS32 ZLAC8015D_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 ZLAC8015D_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 ZLAC8015D_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex ZLAC8015D_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 ZLAC8015D_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 ZLAC8015D_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 ZLAC8015D_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 ZLAC8015D_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex ZLAC8015D_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1600[3] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1602[3] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1603 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1603[3] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 ZLAC8015D_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ZLAC8015D_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ZLAC8015D_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 ZLAC8015D_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ZLAC8015D_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ZLAC8015D_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 ZLAC8015D_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ZLAC8015D_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ZLAC8015D_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 ZLAC8015D_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ZLAC8015D_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 ZLAC8015D_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ZLAC8015D_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ZLAC8015D_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ZLAC8015D_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A00[3] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1A01 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A01[3] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1A02 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A02[3] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 ZLAC8015D_highestSubIndex_obj1A03 = 4; /* number of subindex - 1*/
                    UNS32 ZLAC8015D_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex ZLAC8015D_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ZLAC8015D_obj1A03[3] }
                     };

/* index 0x2000 :   Mapped variable commu_protect */
                    subindex ZLAC8015D_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&commu_protect }
                     };

/* index 0x2001 :   Mapped variable RS485_Node_ID */
                    subindex ZLAC8015D_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&RS485_Node_ID }
                     };

/* index 0x2002 :   Mapped variable RS485_Baud_Rate */
                    subindex ZLAC8015D_Index2002[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&RS485_Baud_Rate }
                     };

/* index 0x2003 :   Mapped variable Input_Status */
                    subindex ZLAC8015D_Index2003[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Input_Status }
                     };

/* index 0x2004 :   Mapped variable Output_Status */
                    subindex ZLAC8015D_Index2004[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Output_Status }
                     };

/* index 0x2005 :   Mapped variable Pos_Feedback_Clear */
                    subindex ZLAC8015D_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Pos_Feedback_Clear }
                     };

/* index 0x2006 :   Mapped variable Abs_Pos_Clear */
                    subindex ZLAC8015D_Index2006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Abs_Pos_Clear }
                     };

/* index 0x2007 :   Mapped variable Enable_PowerOn */
                    subindex ZLAC8015D_Index2007[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Enable_PowerOn }
                     };

/* index 0x2008 :   Mapped variable Motor_Max_Velocity */
                    subindex ZLAC8015D_Index2008[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Max_Velocity }
                     };

/* index 0x2009 :   Mapped variable Factory_Reset */
                    subindex ZLAC8015D_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Factory_Reset }
                     };

/* index 0x200A :   Mapped variable CAN_NodeID */
                    subindex ZLAC8015D_Index200A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_NodeID }
                     };

/* index 0x200B :   Mapped variable CAN_Baud_Rate */
                    subindex ZLAC8015D_Index200B[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CAN_Baud_Rate }
                     };

/* index 0x200C :   Mapped variable Motor_Pole */
                    UNS8 ZLAC8015D_highestSubIndex_obj200C = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index200C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj200C },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Pole[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_Pole[1] }
                     };

/* index 0x200D :   Mapped variable Start_Velocity */
                    UNS8 ZLAC8015D_highestSubIndex_obj200D = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index200D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj200D },
                       { RW, uint16, sizeof (UNS16), (void*)&Start_Velocity[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Start_Velocity[1] }
                     };

/* index 0x200E :   Mapped variable Encoder_Line */
                    UNS8 ZLAC8015D_highestSubIndex_obj200E = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index200E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj200E },
                       { RW, uint16, sizeof (UNS16), (void*)&Encoder_Line[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Encoder_Line[1] }
                     };

/* index 0x200F :   Mapped variable Control_Status */
                    subindex ZLAC8015D_Index200F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Control_Status }
                     };

/* index 0x2010 :   Mapped variable EEPROM_Config */
                    subindex ZLAC8015D_Index2010[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&EEPROM_Config }
                     };

/* index 0x2011 :   Mapped variable Hall_Angle */
                    UNS8 ZLAC8015D_highestSubIndex_obj2011 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2011 },
                       { RW, uint16, sizeof (UNS16), (void*)&Hall_Angle[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Hall_Angle[1] }
                     };

/* index 0x2012 :   Mapped variable Overload_Factor */
                    UNS8 ZLAC8015D_highestSubIndex_obj2012 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2012[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2012 },
                       { RW, uint16, sizeof (UNS16), (void*)&Overload_Factor[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Overload_Factor[1] }
                     };

/* index 0x2013 :   Mapped variable Temperature_Threshold */
                    UNS8 ZLAC8015D_highestSubIndex_obj2013 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2013[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2013 },
                       { RW, uint16, sizeof (UNS16), (void*)&Temperature_Threshold[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Temperature_Threshold[1] }
                     };

/* index 0x2014 :   Mapped variable Rated_Current */
                    UNS8 ZLAC8015D_highestSubIndex_obj2014 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2014[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2014 },
                       { RW, uint16, sizeof (UNS16), (void*)&Rated_Current[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Rated_Current[1] }
                     };

/* index 0x2015 :   Mapped variable Max_Current */
                    UNS8 ZLAC8015D_highestSubIndex_obj2015 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2015[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2015 },
                       { RW, uint16, sizeof (UNS16), (void*)&Max_Current[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Max_Current[1] }
                     };

/* index 0x2016 :   Mapped variable Overload_Protect_timer */
                    UNS8 ZLAC8015D_highestSubIndex_obj2016 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2016 },
                       { RW, uint16, sizeof (UNS16), (void*)&Overload_Protect_timer[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Overload_Protect_timer[1] }
                     };

/* index 0x2017 :   Mapped variable OverPos_Threshold */
                    UNS8 ZLAC8015D_highestSubIndex_obj2017 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2017[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2017 },
                       { RW, uint16, sizeof (UNS16), (void*)&OverPos_Threshold[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&OverPos_Threshold[1] }
                     };

/* index 0x2018 :   Mapped variable velocity_smoothing_factor */
                    UNS8 ZLAC8015D_highestSubIndex_obj2018 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2018 },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_smoothing_factor[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_smoothing_factor[1] }
                     };

/* index 0x2019 :   Mapped variable cl_kp */
                    UNS8 ZLAC8015D_highestSubIndex_obj2019 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2019[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2019 },
                       { RW, uint16, sizeof (UNS16), (void*)&cl_kp[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&cl_kp[1] }
                     };

/* index 0x201A :   Mapped variable cl_ki */
                    UNS8 ZLAC8015D_highestSubIndex_obj201A = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201A },
                       { RW, uint16, sizeof (UNS16), (void*)&cl_ki[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&cl_ki[1] }
                     };

/* index 0x201B :   Mapped variable ff_smoth_factor */
                    UNS8 ZLAC8015D_highestSubIndex_obj201B = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201B },
                       { RW, uint16, sizeof (UNS16), (void*)&ff_smoth_factor[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&ff_smoth_factor[1] }
                     };

/* index 0x201C :   Mapped variable torque_smoth_factor */
                    UNS8 ZLAC8015D_highestSubIndex_obj201C = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201C },
                       { RW, uint16, sizeof (UNS16), (void*)&torque_smoth_factor[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&torque_smoth_factor[1] }
                     };

/* index 0x201D :   Mapped variable vl_kp */
                    UNS8 ZLAC8015D_highestSubIndex_obj201D = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201D },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_kp[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_kp[1] }
                     };

/* index 0x201E :   Mapped variable vl_ki */
                    UNS8 ZLAC8015D_highestSubIndex_obj201E = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201E },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_ki[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_ki[1] }
                     };

/* index 0x201F :   Mapped variable vl_kf */
                    UNS8 ZLAC8015D_highestSubIndex_obj201F = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index201F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj201F },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_kf[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&vl_kf[1] }
                     };

/* index 0x2020 :   Mapped variable pl_kp */
                    UNS8 ZLAC8015D_highestSubIndex_obj2020 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2020 },
                       { RW, uint16, sizeof (UNS16), (void*)&pl_kp[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&pl_kp[1] }
                     };

/* index 0x2021 :   Mapped variable pl_kf */
                    UNS8 ZLAC8015D_highestSubIndex_obj2021 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2021[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2021 },
                       { RW, uint16, sizeof (UNS16), (void*)&pl_kf[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&pl_kf[1] }
                     };

/* index 0x2022 :   Mapped variable velocity_observer_1 */
                    UNS8 ZLAC8015D_highestSubIndex_obj2022 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2022[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2022 },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_1[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_1[1] }
                     };

/* index 0x2023 :   Mapped variable velocity_observer_2 */
                    UNS8 ZLAC8015D_highestSubIndex_obj2023 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2023[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2023 },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_2[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_2[1] }
                     };

/* index 0x2024 :   Mapped variable velocity_observer_3 */
                    UNS8 ZLAC8015D_highestSubIndex_obj2024 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2024[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2024 },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_3[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_3[1] }
                     };

/* index 0x2025 :   Mapped variable velocity_observer_4 */
                    UNS8 ZLAC8015D_highestSubIndex_obj2025 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2025[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2025 },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_4[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&velocity_observer_4[1] }
                     };

/* index 0x2030 :   Mapped variable IO_config */
                    UNS8 ZLAC8015D_highestSubIndex_obj2030 = 8; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2030[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2030 },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[1] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[2] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[3] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[4] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[5] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[6] },
                       { RW, uint16, sizeof (UNS16), (void*)&IO_config[7] }
                     };

/* index 0x2031 :   Mapped variable software_version */
                    subindex ZLAC8015D_Index2031[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&software_version }
                     };

/* index 0x2032 :   Mapped variable motor_temperature */
                    UNS8 ZLAC8015D_highestSubIndex_obj2032 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2032[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2032 },
                       { RO, uint16, sizeof (UNS16), (void*)&motor_temperature[0] },
                       { RO, uint16, sizeof (UNS16), (void*)&motor_temperature[1] }
                     };

/* index 0x2033 :   Mapped variable mortor_status */
                    UNS8 ZLAC8015D_highestSubIndex_obj2033 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2033[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2033 },
                       { RO, uint16, sizeof (UNS16), (void*)&mortor_status[0] },
                       { RO, uint16, sizeof (UNS16), (void*)&mortor_status[1] }
                     };

/* index 0x2034 :   Mapped variable Hall_status */
                    UNS8 ZLAC8015D_highestSubIndex_obj2034 = 2; /* number of subindex - 1*/
                    subindex ZLAC8015D_Index2034[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ZLAC8015D_highestSubIndex_obj2034 },
                       { RO, uint16, sizeof (UNS16), (void*)&Hall_status[0] },
                       { RO, uint16, sizeof (UNS16), (void*)&Hall_status[1] }
                     };

/* index 0x2035 :   Mapped variable DC_voltage */
                    subindex ZLAC8015D_Index2035[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&DC_voltage }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex ZLAC8015D_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex ZLAC8015D_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex ZLAC8015D_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex ZLAC8015D_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex ZLAC8015D_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex ZLAC8015D_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex ZLAC8015D_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex ZLAC8015D_Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex ZLAC8015D_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex ZLAC8015D_Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex ZLAC8015D_Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex ZLAC8015D_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable ZLAC8015D_objdict[] = 
{
  { (subindex*)ZLAC8015D_Index1000,sizeof(ZLAC8015D_Index1000)/sizeof(ZLAC8015D_Index1000[0]), 0x1000},
  { (subindex*)ZLAC8015D_Index1001,sizeof(ZLAC8015D_Index1001)/sizeof(ZLAC8015D_Index1001[0]), 0x1001},
  { (subindex*)ZLAC8015D_Index1005,sizeof(ZLAC8015D_Index1005)/sizeof(ZLAC8015D_Index1005[0]), 0x1005},
  { (subindex*)ZLAC8015D_Index1009,sizeof(ZLAC8015D_Index1009)/sizeof(ZLAC8015D_Index1009[0]), 0x1009},
  { (subindex*)ZLAC8015D_Index100A,sizeof(ZLAC8015D_Index100A)/sizeof(ZLAC8015D_Index100A[0]), 0x100A},
  { (subindex*)ZLAC8015D_Index1014,sizeof(ZLAC8015D_Index1014)/sizeof(ZLAC8015D_Index1014[0]), 0x1014},
  { (subindex*)ZLAC8015D_Index1017,sizeof(ZLAC8015D_Index1017)/sizeof(ZLAC8015D_Index1017[0]), 0x1017},
  { (subindex*)ZLAC8015D_Index1018,sizeof(ZLAC8015D_Index1018)/sizeof(ZLAC8015D_Index1018[0]), 0x1018},
  { (subindex*)ZLAC8015D_Index1200,sizeof(ZLAC8015D_Index1200)/sizeof(ZLAC8015D_Index1200[0]), 0x1200},
  { (subindex*)ZLAC8015D_Index1400,sizeof(ZLAC8015D_Index1400)/sizeof(ZLAC8015D_Index1400[0]), 0x1400},
  { (subindex*)ZLAC8015D_Index1401,sizeof(ZLAC8015D_Index1401)/sizeof(ZLAC8015D_Index1401[0]), 0x1401},
  { (subindex*)ZLAC8015D_Index1402,sizeof(ZLAC8015D_Index1402)/sizeof(ZLAC8015D_Index1402[0]), 0x1402},
  { (subindex*)ZLAC8015D_Index1403,sizeof(ZLAC8015D_Index1403)/sizeof(ZLAC8015D_Index1403[0]), 0x1403},
  { (subindex*)ZLAC8015D_Index1600,sizeof(ZLAC8015D_Index1600)/sizeof(ZLAC8015D_Index1600[0]), 0x1600},
  { (subindex*)ZLAC8015D_Index1601,sizeof(ZLAC8015D_Index1601)/sizeof(ZLAC8015D_Index1601[0]), 0x1601},
  { (subindex*)ZLAC8015D_Index1602,sizeof(ZLAC8015D_Index1602)/sizeof(ZLAC8015D_Index1602[0]), 0x1602},
  { (subindex*)ZLAC8015D_Index1603,sizeof(ZLAC8015D_Index1603)/sizeof(ZLAC8015D_Index1603[0]), 0x1603},
  { (subindex*)ZLAC8015D_Index1800,sizeof(ZLAC8015D_Index1800)/sizeof(ZLAC8015D_Index1800[0]), 0x1800},
  { (subindex*)ZLAC8015D_Index1801,sizeof(ZLAC8015D_Index1801)/sizeof(ZLAC8015D_Index1801[0]), 0x1801},
  { (subindex*)ZLAC8015D_Index1802,sizeof(ZLAC8015D_Index1802)/sizeof(ZLAC8015D_Index1802[0]), 0x1802},
  { (subindex*)ZLAC8015D_Index1803,sizeof(ZLAC8015D_Index1803)/sizeof(ZLAC8015D_Index1803[0]), 0x1803},
  { (subindex*)ZLAC8015D_Index1A00,sizeof(ZLAC8015D_Index1A00)/sizeof(ZLAC8015D_Index1A00[0]), 0x1A00},
  { (subindex*)ZLAC8015D_Index1A01,sizeof(ZLAC8015D_Index1A01)/sizeof(ZLAC8015D_Index1A01[0]), 0x1A01},
  { (subindex*)ZLAC8015D_Index1A02,sizeof(ZLAC8015D_Index1A02)/sizeof(ZLAC8015D_Index1A02[0]), 0x1A02},
  { (subindex*)ZLAC8015D_Index1A03,sizeof(ZLAC8015D_Index1A03)/sizeof(ZLAC8015D_Index1A03[0]), 0x1A03},
  { (subindex*)ZLAC8015D_Index2000,sizeof(ZLAC8015D_Index2000)/sizeof(ZLAC8015D_Index2000[0]), 0x2000},
  { (subindex*)ZLAC8015D_Index2001,sizeof(ZLAC8015D_Index2001)/sizeof(ZLAC8015D_Index2001[0]), 0x2001},
  { (subindex*)ZLAC8015D_Index2002,sizeof(ZLAC8015D_Index2002)/sizeof(ZLAC8015D_Index2002[0]), 0x2002},
  { (subindex*)ZLAC8015D_Index2003,sizeof(ZLAC8015D_Index2003)/sizeof(ZLAC8015D_Index2003[0]), 0x2003},
  { (subindex*)ZLAC8015D_Index2004,sizeof(ZLAC8015D_Index2004)/sizeof(ZLAC8015D_Index2004[0]), 0x2004},
  { (subindex*)ZLAC8015D_Index2005,sizeof(ZLAC8015D_Index2005)/sizeof(ZLAC8015D_Index2005[0]), 0x2005},
  { (subindex*)ZLAC8015D_Index2006,sizeof(ZLAC8015D_Index2006)/sizeof(ZLAC8015D_Index2006[0]), 0x2006},
  { (subindex*)ZLAC8015D_Index2007,sizeof(ZLAC8015D_Index2007)/sizeof(ZLAC8015D_Index2007[0]), 0x2007},
  { (subindex*)ZLAC8015D_Index2008,sizeof(ZLAC8015D_Index2008)/sizeof(ZLAC8015D_Index2008[0]), 0x2008},
  { (subindex*)ZLAC8015D_Index2009,sizeof(ZLAC8015D_Index2009)/sizeof(ZLAC8015D_Index2009[0]), 0x2009},
  { (subindex*)ZLAC8015D_Index200A,sizeof(ZLAC8015D_Index200A)/sizeof(ZLAC8015D_Index200A[0]), 0x200A},
  { (subindex*)ZLAC8015D_Index200B,sizeof(ZLAC8015D_Index200B)/sizeof(ZLAC8015D_Index200B[0]), 0x200B},
  { (subindex*)ZLAC8015D_Index200C,sizeof(ZLAC8015D_Index200C)/sizeof(ZLAC8015D_Index200C[0]), 0x200C},
  { (subindex*)ZLAC8015D_Index200D,sizeof(ZLAC8015D_Index200D)/sizeof(ZLAC8015D_Index200D[0]), 0x200D},
  { (subindex*)ZLAC8015D_Index200E,sizeof(ZLAC8015D_Index200E)/sizeof(ZLAC8015D_Index200E[0]), 0x200E},
  { (subindex*)ZLAC8015D_Index200F,sizeof(ZLAC8015D_Index200F)/sizeof(ZLAC8015D_Index200F[0]), 0x200F},
  { (subindex*)ZLAC8015D_Index2010,sizeof(ZLAC8015D_Index2010)/sizeof(ZLAC8015D_Index2010[0]), 0x2010},
  { (subindex*)ZLAC8015D_Index2011,sizeof(ZLAC8015D_Index2011)/sizeof(ZLAC8015D_Index2011[0]), 0x2011},
  { (subindex*)ZLAC8015D_Index2012,sizeof(ZLAC8015D_Index2012)/sizeof(ZLAC8015D_Index2012[0]), 0x2012},
  { (subindex*)ZLAC8015D_Index2013,sizeof(ZLAC8015D_Index2013)/sizeof(ZLAC8015D_Index2013[0]), 0x2013},
  { (subindex*)ZLAC8015D_Index2014,sizeof(ZLAC8015D_Index2014)/sizeof(ZLAC8015D_Index2014[0]), 0x2014},
  { (subindex*)ZLAC8015D_Index2015,sizeof(ZLAC8015D_Index2015)/sizeof(ZLAC8015D_Index2015[0]), 0x2015},
  { (subindex*)ZLAC8015D_Index2016,sizeof(ZLAC8015D_Index2016)/sizeof(ZLAC8015D_Index2016[0]), 0x2016},
  { (subindex*)ZLAC8015D_Index2017,sizeof(ZLAC8015D_Index2017)/sizeof(ZLAC8015D_Index2017[0]), 0x2017},
  { (subindex*)ZLAC8015D_Index2018,sizeof(ZLAC8015D_Index2018)/sizeof(ZLAC8015D_Index2018[0]), 0x2018},
  { (subindex*)ZLAC8015D_Index2019,sizeof(ZLAC8015D_Index2019)/sizeof(ZLAC8015D_Index2019[0]), 0x2019},
  { (subindex*)ZLAC8015D_Index201A,sizeof(ZLAC8015D_Index201A)/sizeof(ZLAC8015D_Index201A[0]), 0x201A},
  { (subindex*)ZLAC8015D_Index201B,sizeof(ZLAC8015D_Index201B)/sizeof(ZLAC8015D_Index201B[0]), 0x201B},
  { (subindex*)ZLAC8015D_Index201C,sizeof(ZLAC8015D_Index201C)/sizeof(ZLAC8015D_Index201C[0]), 0x201C},
  { (subindex*)ZLAC8015D_Index201D,sizeof(ZLAC8015D_Index201D)/sizeof(ZLAC8015D_Index201D[0]), 0x201D},
  { (subindex*)ZLAC8015D_Index201E,sizeof(ZLAC8015D_Index201E)/sizeof(ZLAC8015D_Index201E[0]), 0x201E},
  { (subindex*)ZLAC8015D_Index201F,sizeof(ZLAC8015D_Index201F)/sizeof(ZLAC8015D_Index201F[0]), 0x201F},
  { (subindex*)ZLAC8015D_Index2020,sizeof(ZLAC8015D_Index2020)/sizeof(ZLAC8015D_Index2020[0]), 0x2020},
  { (subindex*)ZLAC8015D_Index2021,sizeof(ZLAC8015D_Index2021)/sizeof(ZLAC8015D_Index2021[0]), 0x2021},
  { (subindex*)ZLAC8015D_Index2022,sizeof(ZLAC8015D_Index2022)/sizeof(ZLAC8015D_Index2022[0]), 0x2022},
  { (subindex*)ZLAC8015D_Index2023,sizeof(ZLAC8015D_Index2023)/sizeof(ZLAC8015D_Index2023[0]), 0x2023},
  { (subindex*)ZLAC8015D_Index2024,sizeof(ZLAC8015D_Index2024)/sizeof(ZLAC8015D_Index2024[0]), 0x2024},
  { (subindex*)ZLAC8015D_Index2025,sizeof(ZLAC8015D_Index2025)/sizeof(ZLAC8015D_Index2025[0]), 0x2025},
  { (subindex*)ZLAC8015D_Index2030,sizeof(ZLAC8015D_Index2030)/sizeof(ZLAC8015D_Index2030[0]), 0x2030},
  { (subindex*)ZLAC8015D_Index2031,sizeof(ZLAC8015D_Index2031)/sizeof(ZLAC8015D_Index2031[0]), 0x2031},
  { (subindex*)ZLAC8015D_Index2032,sizeof(ZLAC8015D_Index2032)/sizeof(ZLAC8015D_Index2032[0]), 0x2032},
  { (subindex*)ZLAC8015D_Index2033,sizeof(ZLAC8015D_Index2033)/sizeof(ZLAC8015D_Index2033[0]), 0x2033},
  { (subindex*)ZLAC8015D_Index2034,sizeof(ZLAC8015D_Index2034)/sizeof(ZLAC8015D_Index2034[0]), 0x2034},
  { (subindex*)ZLAC8015D_Index2035,sizeof(ZLAC8015D_Index2035)/sizeof(ZLAC8015D_Index2035[0]), 0x2035},
  { (subindex*)ZLAC8015D_Index6040,sizeof(ZLAC8015D_Index6040)/sizeof(ZLAC8015D_Index6040[0]), 0x6040},
  { (subindex*)ZLAC8015D_Index6041,sizeof(ZLAC8015D_Index6041)/sizeof(ZLAC8015D_Index6041[0]), 0x6041},
  { (subindex*)ZLAC8015D_Index6060,sizeof(ZLAC8015D_Index6060)/sizeof(ZLAC8015D_Index6060[0]), 0x6060},
  { (subindex*)ZLAC8015D_Index6061,sizeof(ZLAC8015D_Index6061)/sizeof(ZLAC8015D_Index6061[0]), 0x6061},
  { (subindex*)ZLAC8015D_Index6064,sizeof(ZLAC8015D_Index6064)/sizeof(ZLAC8015D_Index6064[0]), 0x6064},
  { (subindex*)ZLAC8015D_Index606C,sizeof(ZLAC8015D_Index606C)/sizeof(ZLAC8015D_Index606C[0]), 0x606C},
  { (subindex*)ZLAC8015D_Index607A,sizeof(ZLAC8015D_Index607A)/sizeof(ZLAC8015D_Index607A[0]), 0x607A},
  { (subindex*)ZLAC8015D_Index6081,sizeof(ZLAC8015D_Index6081)/sizeof(ZLAC8015D_Index6081[0]), 0x6081},
  { (subindex*)ZLAC8015D_Index6083,sizeof(ZLAC8015D_Index6083)/sizeof(ZLAC8015D_Index6083[0]), 0x6083},
  { (subindex*)ZLAC8015D_Index6084,sizeof(ZLAC8015D_Index6084)/sizeof(ZLAC8015D_Index6084[0]), 0x6084},
  { (subindex*)ZLAC8015D_Index6085,sizeof(ZLAC8015D_Index6085)/sizeof(ZLAC8015D_Index6085[0]), 0x6085},
  { (subindex*)ZLAC8015D_Index60FF,sizeof(ZLAC8015D_Index60FF)/sizeof(ZLAC8015D_Index60FF[0]), 0x60FF},
};

const indextable * ZLAC8015D_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = ZLAC8015D_Index1005_callbacks; break;
		case 0x1009: i = 3;break;
		case 0x100A: i = 4;break;
		case 0x1014: i = 5;break;
		case 0x1017: i = 6;*callbacks = ZLAC8015D_Index1017_callbacks; break;
		case 0x1018: i = 7;break;
		case 0x1200: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1403: i = 12;break;
		case 0x1600: i = 13;break;
		case 0x1601: i = 14;break;
		case 0x1602: i = 15;break;
		case 0x1603: i = 16;break;
		case 0x1800: i = 17;*callbacks = ZLAC8015D_Index1800_callbacks; break;
		case 0x1801: i = 18;*callbacks = ZLAC8015D_Index1801_callbacks; break;
		case 0x1802: i = 19;*callbacks = ZLAC8015D_Index1802_callbacks; break;
		case 0x1803: i = 20;*callbacks = ZLAC8015D_Index1803_callbacks; break;
		case 0x1A00: i = 21;break;
		case 0x1A01: i = 22;break;
		case 0x1A02: i = 23;break;
		case 0x1A03: i = 24;break;
		case 0x2000: i = 25;break;
		case 0x2001: i = 26;break;
		case 0x2002: i = 27;break;
		case 0x2003: i = 28;break;
		case 0x2004: i = 29;break;
		case 0x2005: i = 30;break;
		case 0x2006: i = 31;break;
		case 0x2007: i = 32;break;
		case 0x2008: i = 33;break;
		case 0x2009: i = 34;break;
		case 0x200A: i = 35;break;
		case 0x200B: i = 36;break;
		case 0x200C: i = 37;break;
		case 0x200D: i = 38;break;
		case 0x200E: i = 39;break;
		case 0x200F: i = 40;break;
		case 0x2010: i = 41;break;
		case 0x2011: i = 42;break;
		case 0x2012: i = 43;break;
		case 0x2013: i = 44;break;
		case 0x2014: i = 45;break;
		case 0x2015: i = 46;break;
		case 0x2016: i = 47;break;
		case 0x2017: i = 48;break;
		case 0x2018: i = 49;break;
		case 0x2019: i = 50;break;
		case 0x201A: i = 51;break;
		case 0x201B: i = 52;break;
		case 0x201C: i = 53;break;
		case 0x201D: i = 54;break;
		case 0x201E: i = 55;break;
		case 0x201F: i = 56;break;
		case 0x2020: i = 57;break;
		case 0x2021: i = 58;break;
		case 0x2022: i = 59;break;
		case 0x2023: i = 60;break;
		case 0x2024: i = 61;break;
		case 0x2025: i = 62;break;
		case 0x2030: i = 63;break;
		case 0x2031: i = 64;break;
		case 0x2032: i = 65;break;
		case 0x2033: i = 66;break;
		case 0x2034: i = 67;break;
		case 0x2035: i = 68;break;
		case 0x6040: i = 69;break;
		case 0x6041: i = 70;break;
		case 0x6060: i = 71;break;
		case 0x6061: i = 72;break;
		case 0x6064: i = 73;break;
		case 0x606C: i = 74;break;
		case 0x607A: i = 75;break;
		case 0x6081: i = 76;break;
		case 0x6083: i = 77;break;
		case 0x6084: i = 78;break;
		case 0x6085: i = 79;break;
		case 0x60FF: i = 80;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ZLAC8015D_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ZLAC8015D_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index ZLAC8015D_firstIndex = {
  8, /* SDO_SVR */
  0, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const quick_index ZLAC8015D_lastIndex = {
  8, /* SDO_SVR */
  0, /* SDO_CLT */
  12, /* PDO_RCV */
  16, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  24 /* PDO_TRS_MAP */
};

const UNS16 ZLAC8015D_ObjdictSize = sizeof(ZLAC8015D_objdict)/sizeof(ZLAC8015D_objdict[0]); 

CO_Data ZLAC8015D_Data = CANOPEN_NODE_DATA_INITIALIZER(ZLAC8015D);

